import { ApiProvider } from "../../context/ApiContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

const LoginLayout: React.FC<Props> = ({ children }) => {

  return (
    <>
        <ApiProvider> 
            {children}           
        </ApiProvider>
    </>
  );
}

export default LoginLayout;
