import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ApiProvider } from "@/context/ApiContext";
import Navbar from "../components/NavBar/navbar";
import Footer from "../components/Footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


interface MainLayoutProps {
  children: React.ReactNode;
}

export default function MainLayout({ children } : MainLayoutProps) {

  return (
    <>
     <ApiProvider> 
          <Navbar />
               {children}
          <Footer />
     </ApiProvider>
    </>
  );
}
