import { Geist, Geist_Mono } from "next/font/google";
import { ApiProvider } from "../../context/ApiContext";
import { AppSidebar } from "@/components/SideBar/AppSidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import "../../custom-css/calendar-custom.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

const LoginLayout: React.FC<Props> = ({ children }) => {

  return (
    <>
        <ApiProvider> 
          <SidebarProvider>
              <AppSidebar />
              <main className="w-full">
              <SidebarTrigger />
              {children}
              </main>         
          </SidebarProvider>
        </ApiProvider>
    </>
  );
}

export default LoginLayout;
